const express = require('express');
const router = express.Router();
const controller = require('../controller/controller');
router.route('/').get(controller.getFun);
router.route('/token').post(controller.getToken);
router.route('/verify').post(controller.decToken);
router.route('/buyer/otp_buyer').post(controller.buyerRegisterOtp);
router.route('/buyer/register_buyer').post(controller.signUpBuyer);
router.route('/buyer/login_buyer').post(controller.loginBuyer);
router.route('/buyer/pass_update_email').post(controller.buyerPassUpdate);
router.route('/buyer/pass_update_id').post(controller.resetBuyerPass);
module.exports = router;